// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzy8fUJcSdrjTMMm5SRlkfdBk9AxzXTw',
    appId: '1:326212357933:web:5978be8b543ffa5e8bcda4',
    messagingSenderId: '326212357933',
    projectId: 'library01-dbeb4',
    authDomain: 'library01-dbeb4.firebaseapp.com',
    storageBucket: 'library01-dbeb4.firebasestorage.app',
    measurementId: 'G-CWSHBVNHSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TnKcI-pGQeg0phpTlrX5SYKRG0CT7Hs',
    appId: '1:326212357933:android:83fd44026357d3158bcda4',
    messagingSenderId: '326212357933',
    projectId: 'library01-dbeb4',
    storageBucket: 'library01-dbeb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Kwy26dWezV-S4OgNezxHjFo0Z5cijGU',
    appId: '1:326212357933:ios:c7c0caecc3ae2c318bcda4',
    messagingSenderId: '326212357933',
    projectId: 'library01-dbeb4',
    storageBucket: 'library01-dbeb4.firebasestorage.app',
    iosBundleId: 'com.example.library01',
  );
}
